### ISSUE TITLE
The player cannot get authenticated after restarting the game

### ISSUE THREAD

**Issue by thedoctor2001** [project-SIMPLE/simple.webplatform#34]
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] -> The player Player_122 disconnected
[0] [DEBUG Player Player_122] Receiving state update {"type":"json_state","id_player":"Player_122","connected":true,"in_game":true,"date_connection":"16:50"}
[0] -> The last message received from Player_122 created an internal error.
[0] TypeError: Cannot read properties of undefined (reading 'jsonGamaState')
[0]     at PlayerManager.addPlayerConnection (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/src/api/PlayerManager.ts:259:77)
[0]     at WebSocket.<anonymous> (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/src/api/PlayerManager.ts:74:38)
[0]     at WebSocket.emit (node:events:520:28)
[0]     at Receiver.receiverOnMessage (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/node_modules/ws/lib/websocket.js:1220:20)
[0]     at Receiver.emit (node:events:520:28)
[0]     at Receiver.dataMessage (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/node_modules/ws/lib/receiver.js:596:14)
[0]     at Receiver.getData (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/node_modules/ws/lib/receiver.js:496:10)
[0]     at Receiver.startLoop (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/node_modules/ws/lib/receiver.js:167:16)
[0]     at Receiver._write (/Users/nguyenthanhdo/Documents/GitHub/GamaServerMiddleware/node_modules/ws/lib/receiver.js:94:10)
[0]     at writeOrBuffer (node:internal/streams/writable:570:12)
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] Sending ping to Player_122
[0] [CONNECTOR] Remove player Player_122
[0] [GAMA CONNECTOR] Removing player from game: Player_122
[0] [PLAYER MANAGER] Deleting player Player_122
[0] [PLAYER MANAGER] Something strange happened while try to change in_game status for Player_122 false

**Comment by RoiArthurB** [comment]
Should be fixed since 9e149e8eaaa0e08b947f0d5fae0cc9da7255dc53 however, since your template doesn't have the latest commit implementing a callback in GAMA to re-send the initialization message; you'll probably won't be able to play again.

---

Can you try if the reconnection - authentification works tho please ? :)

**Comment by RoiArthurB** [comment]
Closing as it doesn't seem to be an issue anymore. Please re-open if happening again :)
